INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 5000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 10000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 15000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 20000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 25000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 30000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 35000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 40000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 45000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 50000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 55000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 60000KM. A');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 60000KM. B');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 65000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 70000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 75000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 80000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 85000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 90000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 95000KM.');
INSERT INTO TiposMantenimientos(NombreMantenimiento) VALUES('MANTENIMIENTO DE 100000KM.');

INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Afinado de motor.                                             ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Agua refrigerante de motor                                    ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Alineado y balanceado de ruedas.                              ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Balanceo de llantas.                                          ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Bujías.                                                       ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar aceite de caja y/o diferenciales.                     ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar aceite de motor.                                      ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar aceite de sistema de transferencia.                   ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar aceite de sistema de transmisión manual.              ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar filtro aire.                                          ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar filtro de aceite.                                     ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambiar filtro de polen.                                      ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Cambio correa de distribución.                                ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Engrase cardan modelos 4x4                                    ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Engrase rodamientos de maseros.                               ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspección de líquido de frenos y/o embrague.                 ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspeccion de sistema de dirección.                           ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('inspección filtro de combustible.                             ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspección funcionamiento de motor.                           ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspeccion nivel de agua deposito limpiaparabrisas.           ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspeccion nivel de líquido refrigerante.                     ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspección nivel de solución de batería.                      ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspeccion sistema de dirección.                              ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspeccion sistema de suspensión.                             ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Inspeccion y limpieza de frenos.                              ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Limpieza e inspección chisguete y escobillas limpiaparabrisas ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Limpieza y calibrado de inyectores.                           ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Lubricado de bisagras de puertas.                             ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Regulado de embrague.                                         ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Revisión de luces en general.                                 ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Revisión de niveles en general.                               ');
INSERT INTO ActividadesMantenimiento(NombreActividad) VALUES('Revisión presión de llantas.                                  ');

