insert into categorias (nombrecategoria) values ('Aceites vegetales');
insert into categorias (nombrecategoria) values ('Grasas animales');
insert into categorias (nombrecategoria) values ('Accesorios de materiales textiles');
insert into categorias (nombrecategoria) values ('Alfombras y tapicería');
insert into categorias (nombrecategoria) values ('Algodón');
insert into categorias (nombrecategoria) values ('Calzados');
insert into categorias (nombrecategoria) values ('Demás artículos confeccionados');
insert into categorias (nombrecategoria) values ('Demás productos textiles');
insert into categorias (nombrecategoria) values ('Fibras sintéticas, sus hilados y tejidos');
insert into categorias (nombrecategoria) values ('Hilados y tejidos de algodón');
insert into categorias (nombrecategoria) values ('Prendas de vestir de punto');
insert into categorias (nombrecategoria) values ('Prendas de vestir, no de punto');
insert into categorias (nombrecategoria) values ('Ropa de cama, mesa, tocador o cocina, mantas');
insert into categorias (nombrecategoria) values ('Seda');
insert into categorias (nombrecategoria) values ('Almidón');
insert into categorias (nombrecategoria) values ('Azúcares');
insert into categorias (nombrecategoria) values ('Bebidas');
insert into categorias (nombrecategoria) values ('Demás alimentos preparados');
insert into categorias (nombrecategoria) values ('Esteviósido');
insert into categorias (nombrecategoria) values ('Harinas y grañones');
insert into categorias (nombrecategoria) values ('Lácteos');
insert into categorias (nombrecategoria) values ('Melaza');
insert into categorias (nombrecategoria) values ('Panadería y Pastelería');
insert into categorias (nombrecategoria) values ('Carbón y leña');
insert into categorias (nombrecategoria) values ('Madera aserrada');
insert into categorias (nombrecategoria) values ('Madera chapada');
insert into categorias (nombrecategoria) values ('Madera en bruto');
insert into categorias (nombrecategoria) values ('Madera para pisos');
insert into categorias (nombrecategoria) values ('Muebles');
insert into categorias (nombrecategoria) values ('Otros productos de madera');
insert into categorias (nombrecategoria) values ('Animales vivos');
insert into categorias (nombrecategoria) values ('Carne bovina congelada');
insert into categorias (nombrecategoria) values ('Carne bovina fresca o refrigerada');
insert into categorias (nombrecategoria) values ('Carne de ave');
insert into categorias (nombrecategoria) values ('Carnes procesadas');
insert into categorias (nombrecategoria) values ('Cueros bovinos o equinos');
insert into categorias (nombrecategoria) values ('Despojos de carne');
insert into categorias (nombrecategoria) values ('Productos animales no comestibles');
insert into categorias (nombrecategoria) values ('Productos de cuero');
insert into categorias (nombrecategoria) values ('Arroz');
insert into categorias (nombrecategoria) values ('Demás cereales');
insert into categorias (nombrecategoria) values ('Maíz');
insert into categorias (nombrecategoria) values ('Oleaginosas distintas a la soja');
insert into categorias (nombrecategoria) values ('Soja');
insert into categorias (nombrecategoria) values ('Trigo');
insert into categorias (nombrecategoria) values ('Artículos para baño de cerámica');
insert into categorias (nombrecategoria) values ('Demás manufacturas de cerámica');
insert into categorias (nombrecategoria) values ('Ladrillos, tejas y tubs de cerámica');
insert into categorias (nombrecategoria) values ('Placas y baldosas de cerámica');
insert into categorias (nombrecategoria) values ('Vidrios');
insert into categorias (nombrecategoria) values ('Demás productos manufacturados');
insert into categorias (nombrecategoria) values ('Juegos, juguetes y artículos deportivos');
insert into categorias (nombrecategoria) values ('Papeles y cartones');
insert into categorias (nombrecategoria) values ('Productos para procesamiento de papel');
insert into categorias (nombrecategoria) values ('Café, té y Yerba Mate');
insert into categorias (nombrecategoria) values ('Frutas');
insert into categorias (nombrecategoria) values ('Hierbas medicinales, Stevia y demás hierbas');
insert into categorias (nombrecategoria) values ('Hortalizas');
insert into categorias (nombrecategoria) values ('Jugos de frutas o de hortalizas');
insert into categorias (nombrecategoria) values ('Cosmético');
insert into categorias (nombrecategoria) values ('Farmacéutico');
insert into categorias (nombrecategoria) values ('Aparatos eléctricos');
insert into categorias (nombrecategoria) values ('Instrumentos de precisión');
insert into categorias (nombrecategoria) values ('Materiales de transporte terrestre');
insert into categorias (nombrecategoria) values ('Máquinas industriales y accesorios');
insert into categorias (nombrecategoria) values ('Soportes para la grabación');
insert into categorias (nombrecategoria) values ('Aluminio y sus manufacturas');
insert into categorias (nombrecategoria) values ('Chapas, varillas, perfiles etc. de hierro y acero');
insert into categorias (nombrecategoria) values ('Cobre y sus manufacturas');
insert into categorias (nombrecategoria) values ('Herramientas y utensilios de metal');
insert into categorias (nombrecategoria) values ('Hierro y acero en formas primarias');
insert into categorias (nombrecategoria) values ('Manufacturas de hierro y acero');
insert into categorias (nombrecategoria) values ('Balanceado para animales');
insert into categorias (nombrecategoria) values ('Demás pelets y forrajes');
insert into categorias (nombrecategoria) values ('Pelets y tortas de soja');
insert into categorias (nombrecategoria) values ('Art. p/ el transp. o envasado, de plást.');
insert into categorias (nombrecategoria) values ('Caucho en formas primarias');
insert into categorias (nombrecategoria) values ('Demás manufacturas de caucho');
insert into categorias (nombrecategoria) values ('Demás manufacturas de plástico');
insert into categorias (nombrecategoria) values ('Neumáticos');
insert into categorias (nombrecategoria) values ('Plástico en formas primarias');
insert into categorias (nombrecategoria) values ('Alcoholes');
insert into categorias (nombrecategoria) values ('Demás productos químicos');
insert into categorias (nombrecategoria) values ('Detergentes');
insert into categorias (nombrecategoria) values ('Insecticidas y demás plaguicidas');
insert into categorias (nombrecategoria) values ('Minerales');
insert into categorias (nombrecategoria) values ('Piedras');
insert into categorias (nombrecategoria) values ('Productos de química anorgánica');
insert into categorias (nombrecategoria) values ('Productos de química orgánica');
insert into categorias (nombrecategoria) values ('Tabacos');
