INSERT INTO articulos (NombreArticulo, IdCategoria, CantidadExistencia, PrecioVigente, TipoInventario, Descripcion) VALUES 
('Té Dharamsala', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cerveza tibetana Barley', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Sirope de regaliz', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Especias Cajun del chef Anton', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Mezcla Gumbo del chef Anton', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Mermelada de grosellas de la abuela', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Peras secas orgánicas del tío Bob', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Salsa de arándanos Northwoods', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Buey Mishi Kobe', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Pez espada', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso Cabrales', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso Manchego La Pastora', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Algas Konbu', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cuajada de judías', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Salsa de soja baja en sodio', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Postre de merengue Pavlova', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cordero Alice Springs', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Langostinos tigre Carnarvon', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Pastas de té de chocolate', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Mermelada de Sir Rodneys', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Bollos de Sir Rodneys', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Pan de centeno crujiente estilo Gustafs', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Pan fino', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Refresco Guaraná Fantástica', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Crema de chocolate y nueces NuNuCa', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Ositos de goma Gumbär', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Chocolate Schoggi', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Col fermentada Rössle', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Salchicha Thüringer', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Arenque blanco del noroeste', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso gorgonzola Telino', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso Mascarpone Fabioli', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso de cabra', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cerveza Sasquatch', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cerveza negra Steeleye', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Escabeche de arenque', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Salmón ahumado Gravad', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Vino Côte de Blaye', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Licor verde Chartreuse', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Carne de cangrejo de Boston', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Crema de almejas estilo Nueva Inglaterra', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Tallarines de Singapur', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Café de Malasia', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Azúcar negra Malacca', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Arenque ahumado', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Arenque salado', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Galletas Zaanse', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Chocolate holandés', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Regaliz', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Chocolate blanco', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Manzanas secas Manjimup', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cereales para Filo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Empanada de carne', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Empanada de cerdo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Paté chino', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Gnocchi de la abuela Alicia', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Raviolis Angelo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Caracoles de Borgoña', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Raclet de queso Courdavault', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Camembert Pierrot', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Sirope de arce', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Tarta de azúcar', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Sandwich de vegetales', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Bollos de pan de Wimmer', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Salsa de pimiento picante de Luisiana', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Especias picantes de Luisiana', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cerveza Laughing Lumberjack', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Barras de pan de Escocia', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso Gudbrandsdals', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cerveza Outback', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Crema de queso Fløtemys', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso Mozzarella Giovanni', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Caviar rojo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Queso de soja Longlife', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Cerveza Klosterbier Rhönbräu', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Licor Cloudberry', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL),
('Salsa verde original Frankfurter', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 'P', NULL);


